my_blog/history/urls.py
from django.urls import path

from history import views

app_name = "history"
urlpatterns = [
    path("historys/", views.HistoryListView.as_view(), name="history-list"),
    path("history/add/", views.HistoryCreateView.as_view(), name="history-add"),
    path("history/<int:pk>/detail/", views.HistoryDetailView.as_view(), name="history-detail"),
    path("history/<int:pk>/update/", views.HistoryUpdateView.as_view(), name="history-update"),
    path("history/<int:pk>/delete/", views.HistoryDeleteView.as_view(), name="history-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("history/", include("history.urls")),
    path("hobbie/", include("hobbie.urls")),
    path("shop/", include("shop.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/history/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField


class History(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)
    code = models.IntegerField(null=False, blank=False)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='history', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "name",
            "code",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Historia: {self.name} | #: {self.code}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    history = models.ForeignKey(History, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

my_blog/history/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from history.models import History


class HistoryForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre de tu historia",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "history-name",
                "placeholder": "Nombre de tu historia",
                "required": "True",
            }
        ),
    )

    code = forms.IntegerField(
        label="# Publicacion",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "history-code",
                "placeholder": "# Publicacion",
                "required": "True",
            }
        ),
    )

    description = forms.CharField(
        label="Historia:",
        required=False,
        widget=CKEditorWidget(),
    )

    image = forms.ImageField()

    class Meta:
        model = History
        fields = ["name", "code", "description", "image"]


class CommentForm(forms.Form):
    comment_text = forms.CharField(
        label="",
        required=False,
        max_length=500,
        min_length=10,
        strip=True,
        widget=forms.Textarea(
            attrs={
                "class": "comment-text",
                "placeholder": "Ingrese su comentario...",
                "required": "True",
                "max_length": 500,
                "min_length": 10,
                "rows": 2,
                "cols": 10,
                "style":"min-width: 100%",
            }
        ),
    )

my_blog/history/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from history.forms import CommentForm
from history.forms import HistoryForm

from history.models import Comment
from history.models import History



class HistoryListView(ListView):
    model = History
    paginate_by = 3


class HistoryDetailView(DetailView):
    model = History
    template_name = "history/history_detail.html"
    fields = ["name", "code", "description"]

    def get(self, request, pk):
        history = History.objects.get(id=pk)
        comments = Comment.objects.filter(history=history).order_by("-updated_at")
        comment_form = CommentForm()
        context = {
            "history": history,
            "comments": comments,
            "comment_form": comment_form,
        }
        return render(request, self.template_name, context)


class HistoryCreateView(LoginRequiredMixin, CreateView):
    model = History
    success_url = reverse_lazy("history:history-list")

    form_class = HistoryForm
    # fields = ["name", "code", "description"]

    def form_valid(self, form):
        """Filter to avoid duplicate historys"""
        data = form.cleaned_data
        form.instance.owner = self.request.user
        actual_objects = History.objects.filter(
            name=data["name"], code=data["code"]
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"La historia {data['name']} - {data['code']} ya existe, crea una nueva",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Historia {data['name']} - {data['code']} creada exitosamente!",
            )
            return super().form_valid(form)


class HistoryUpdateView(LoginRequiredMixin, UpdateView):
    model = History
    fields = ["name", "code", "description", "image"]

    def get_success_url(self):
        history_id = self.kwargs["pk"]
        return reverse_lazy("history:history-detail", kwargs={"pk": history_id})


class HistoryDeleteView(LoginRequiredMixin, DeleteView):
    model = History
    success_url = reverse_lazy("history:history-list")


class CommentCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, pk):
        history = get_object_or_404(History, id=pk)
        comment = Comment(
            text=request.POST["comment_text"], owner=request.user, history=history
        )
        comment.save()
        return redirect(reverse("history:history-detail", kwargs={"pk": pk}))


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        history = self.object.history
        return reverse("history:history-detail", kwargs={"pk": history.id})

my_blog/history/templates/history/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Eliminar comentario
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Eliminar Comentario</h1>
                    <p class="col-lg-10 fs-4 subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h3 class="col-lg-10 fs-4 subheading">Estás seguro de eliminar el siguiente Comentario?</h3>
<p class="col-lg-10 fs-4 subheading">{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger text-uppercase" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary text-uppercase" href="{% url 'history:history-detail' comment.history.id %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/history/templates/history/history_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Eliminar Historia
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ history.name }}</h1>
                    <p class="col-lg-10 fs-4 subheading">Eliminar hitoria</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<h3 class="col-lg-10 fs-4 subheading">Estás seguro de eliminar la historia: {{ history.name }}?</h3>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger text-uppercase" type="submit" value="Si, eliminar">
    <a class="btn btn-primary text-uppercase" href="{% url 'history:history-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/history/templates/history/history_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Detalle de historia
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ history.name }}</h1>
                    <p class="col-lg-10 fs-4 subheading">Detalles de tu historia</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'history:history-add' %}">Cuentame tu historia</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="col-lg-10 fs-4 subheading">Código: {{ history.code }}</h3>
    <p class="post-meta">
        Creado por
        <span>{{ history.owner.username }}</span>
        ( {{ history.created_at }} )
        <br>
        Última fecha de actualización ( {{ history.updated_at }} )
    </p>

    <!-- Image -->
    {% if history.image %}
        <div style="text-align: center;">
            <img class="img-fluid rounded-3 shadow-lg mb-4 d-block mx-lg-auto" src="{{ history.image.url }}">
        </div>
    {% endif %}

    <!-- Description -->
    <p class="card-text ">{{ history.description|safe }}</p> <!-- ckeditor-->

    <!-- Update-Delete link only for the owner -->
    {% if user == history.owner or user.is_superuser %}
    <div class="mx-auto">
        <a class="btn btn-primary text-uppercase" href="{% url 'history:history-update' history.id %}"><i class="fa fa-pencil"></i> Editar pasatiempo</a>
        <a class="btn btn-primary text-uppercase" href="{% url 'history:history-delete' history.id %}"><i class="fa fa-trash"></i> Eliminar pasatiempo</a>
    </div>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="POST" action="{% url 'history:comment-create' history.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'history:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}
</div>
{% endblock %}

my_blog/history/templates/history/history_form.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Crea tu Historia
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Crea y edita tus historias</h1>
                    <p class="col-lg-10 fs-4 subheading">El diario de Arletina</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary text-uppercase" value="Publicar historia" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/history/templates/history/history_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Mis Historias
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Historias</h1>
                    <p class="col-lg-10 fs-4 subheading">El diario de Arletina</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'history:history-add' %}">Cuentame tu historia</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<h3 class="col-lg-10 fs-4 subheading">Platica entre amigas</h3>
<hr class="my-4" />
    {% for history in history_list %}
    
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'history:history-detail' history.id %}">
                <h3 class="col-lg-10 fs-4 subheading">Hisotoria - {{ history.name }}</h3>
                <small class="post-subtitle"># Publicación {{ history.code }}</small>
            </a>
            <p class="post-meta">
                Creado por
                <span>{{ history.owner.username }}</span>
                ( {{ history.created_at }} )
            </p>
            <div class="mx-auto">
                <a class="btn btn-primary text-uppercase" href="{% url 'history:history-detail' history.id %}">Leer mas →</a>
            </div>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}