my_blog/history/urls.py
from django.urls import path

from history import views

app_name = "history"
urlpatterns = [
    path("historys/", views.HistoryListView.as_view(), name="history-list"),
    path("history/add/", views.HistoryCreateView.as_view(), name="history-add"),
    path("history/<int:pk>/detail/", views.HistoryDetailView.as_view(), name="history-detail"),
    path("history/<int:pk>/update/", views.HistoryUpdateView.as_view(), name="history-update"),
    path("history/<int:pk>/delete/", views.HistoryDeleteView.as_view(), name="history-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),
]

my_blog/hobbie/urls.py
from django.urls import path

from hobbie import views

app_name = "hobbie"
urlpatterns = [
    path("hobbies", views.HobbieListView.as_view(), name="hobbie-list"),
    path("hobbie/add/", views.HobbieCreateView.as_view(), name="hobbie-add"),
    path("hobbie/<int:pk>/detail/", views.HobbieDetailView.as_view(), name="hobbie-detail"),
    path("hobbie/<int:pk>/update/", views.HobbieUpdateView.as_view(), name="hobbie-update"),
    path("hobbie/<int:pk>/delete/", views.HobbieDeleteView.as_view(), name="hobbie-delete"),
]

my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("history/", include("history.urls")),
    path("hobbie/", include("hobbie.urls")),
    path("shop/", include("shop.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"
urlpatterns = [
    path("shops", views.ShopListView.as_view(), name="shop-list"),
    path("shop/add/", views.ShopCreateView.as_view(), name="shop-add"),
    path("shop/<int:pk>/detail/", views.ShopDetailView.as_view(), name="shop-detail"),
    path("shop/<int:pk>/update/", views.ShopUpdateView.as_view(), name="shop-update"),
    path("shop/<int:pk>/delete/", views.ShopDeleteView.as_view(), name="shop-delete"),
]

my_blog/history/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from ckeditor.fields import RichTextField


class History(models.Model):
    name = models.CharField(max_length=40, null=False, blank=False)
    code = models.IntegerField(null=False, blank=False)
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='history', null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(
        User, through="Comment", related_name="comments_owned"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            "name",
            "code",
        )
        ordering = ["-created_at"]

    def __str__(self):
        return f"Historia: {self.name} | #: {self.code}"


class Comment(models.Model):
    text = models.TextField(
        validators=[
            MinLengthValidator(10, "El comentario debe ser mayor de 10 caracteres")
        ]
    )
    history = models.ForeignKey(History, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

my_blog/home/models.py
from django.contrib.auth.models import User
from django.db import models


class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatar', null=True, blank=True)

    def __str__(self):
        return f'user: {self.user.username} | url: {self.image.url}'

my_blog/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from home.models import Avatar

class UserRegisterForm(UserCreationForm):

    username = forms.CharField(label="Alias de usuario", min_length=3)
    first_name = forms.CharField(label="Nombre", min_length=3)
    last_name = forms.CharField(label="Apellido", min_length=3)
    email = forms.EmailField(label="Correo electrónico")
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
        ]
        widgets = {
            "email": forms.TextInput(attrs={"readonly": "readonly"}),
        }


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ("image", )
        

my_blog/home/views.py
import os
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.forms.models import model_to_dict
from django.shortcuts import redirect
from django.shortcuts import render

from history.models import History
from home.forms import AvatarForm
from home.forms import UserRegisterForm
from home.forms import UserUpdateForm
from home.models import Avatar


def get_avatar_url_ctx(request):
    avatars = Avatar.objects.filter(user=request.user.id)
    if avatars.exists():
        return {"avatar_url": avatars[0].image.url}
    return {}


def index(request):
    return render(
        request=request,
        context=get_avatar_url_ctx(request),
        template_name="home/index.html",
    )


def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add(Q(code__contains=search_param), Q.OR)
        historys = History.objects.filter(query)
        context_dict.update(
            {
                "historys": historys,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )


def register(request):
    form = UserRegisterForm(request.POST) if request.POST else UserRegisterForm()
    if request.method == "POST":
        if form.is_valid():
            form.save()
            messages.success(request, "Usuario creado exitosamente!")
            return redirect("login")

    return render(
        request=request,
        context={"form": form},
        template_name="registration/register.html",
    )


@login_required
def user_update(request):
    user = request.user
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("home:index")

    form = UserUpdateForm(model_to_dict(user))
    return render(
        request=request,
        context={"form": form},
        template_name="registration/user_form.html",
    )


@login_required
def avatar_load(request):
    if request.method == "POST":
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid and len(request.FILES) != 0:
            image = request.FILES["image"]
            avatars = Avatar.objects.filter(user=request.user.id)
            if not avatars.exists():
                avatar = Avatar(user=request.user, image=image)
            else:
                avatar = avatars[0]
                if len(avatar.image) > 0:
                    os.remove(avatar.image.path)
                avatar.image = image
            avatar.save()
            messages.success(request, "Imagen cargada exitosamente")
            return redirect("home:index")

    form = AvatarForm()
    return render(
        request=request,
        context={"form": form},
        template_name="home/avatar_form.html",
    )

my_blog/home/templates/home/avatar_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Avatar Load
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Cargar imagen de avatar</h1>
                    <p class="col-lg-10 fs-4 subheading">El diario de Arletina</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<h3 class="col-lg-10 fs-4 subheading">Usuario: {{user.username}} | {{user.first_name}} {{user.last_name}}</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary text-uppercase">Cargar imagen</button>
    </form>
{% endblock %}

my_blog/home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block my_blog_title %}
                Home
            {% endblock %}
        </title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light topbar" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'history:history-list' %}">Mi diario</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'hobbie:hobbie-list' %}">Pasatiempos</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'shop:shop-list' %}">Shop</a></li>
                        
                        <div class="topbar-divider d-none d-sm-block"></div>
                       
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'home:user-update' %}">Editar usuario</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'logout' %}">Cerrar Sesión - {{ user.username }}</a></li>
                        {% else %}
                        <li class="nav-item"><a class="btn btn-primary text-uppercase" href="{% url 'login' %}">Ingresar →</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block my_blog_header %}
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row align-items-center gx-4 gx-lg-5">
                    <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                        <div class="text-center text-lg-start site-heading">
                            {% if user.is_authenticated %}
                                <h4 class="display-4 fw-bold lh-1 mb-3">Bienvenido</h4>
                                <h3 class="col-lg-10 fs-4 subheading">{{ user.first_name }} {{ user.last_name }}</h3>
                            {% else %}
                                <h1 class="display-4 fw-bold lh-1 mb-3">El diario de Arletina</h1>
                                <p class="col-lg-10 fs-4 subheading">De ama de casa a crossfitera y empresaria.</p>
                            {% endif %}
                            {% if avatar_url %}
                                <a href="{% url 'home:avatar-load' %}"><img class="rounded" height="160px" src="{{avatar_url}}"></a></div>
                            {% endif %}
                            {% if not avatar_url %}
                            <div class="mx-auto">

                                <a class="btn btn-primary text-uppercase" href="{% url 'home:avatar-load' %}">Crear avatar</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Messages-->
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                        <!-- Divider-->
                        <hr class="my-4" />
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- Main Content-->

        <div class="container mt-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    {% block my_blog_content %}
                    <div class="card">              
                            <div class="input-box">
                                <form action="{% url 'home:search' %}" method="GET"> 
                                    <input type="text" class="form-control" name="search_param" id="history_code_or_name" placeholder="Buscar.."
                                    {% if search_param %} value="{{ search_param }}" {% endif %}>
                                </form>              
                            </div>
                        {% if historys %}
                        {% for history in historys %}
                        <div class="list border-bottom">
                            <div class="d-flex flex-column ml-3 post-preview">
                                <a href="{% url 'history:history-detail' history.id %}">
                                    <h5 class="post-title">Mi diario {{ history.name }}</h5> 
                                    <small class="post-subtitle"># Publicación {{ history.code }}</small>
                                </a>
                                <p class="post-meta">
                                Creado por
                                <a href="#!">{{ history.owner.username }}</a>
                                ( {{ history.created_at }} )
                                </p>
                            </div>                   
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endblock %}

                        {% block pagination %}
                        <!--Pagination Class Based Views-->
                        {% if is_paginated %}
                        <div class="container p-4">
                            <div class="pagination justify-content-center">
                                <span class="step-links">
                                    {% if page_obj.has_previous %}
                                        <a href="?page=1">&laquo; first</a> |
                                        <a href="?page={{ history_list.previous_page_number }}">previous</a> |
                                    {% endif %}
                        
                                    {% if page_obj.paginator.num_pages > 1 %}
                                    <span class="current">
                                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} |
                                    </span>
                                    {% endif %}
                        
                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">next</a> |
                                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                        {% endif %}
                        <!--end of Pagination-->
                    {% endblock %}
                    </div>             
                </div>           
            </div>         
        </div>

        
        <div class="container col-xxl-8 px-4 py-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                <div class="col-10 col-sm-8 col-lg-6">
                    <img src="/static/home/assets/img/sobre_mi.jpg" class="img-fluid rounded-3 shadow-lg mb-4 d-block mx-lg-auto" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6">
                    <h1 class="display-5 fw-bold lh-1 mb-3">Algo sobre mí</h1>
                    <p class="lead">Un día decidi tomar nuevos rumbos en mi vida y decidi pasar de ser ama de casa a empresaria y crossfitera. Actualmente me encuentro diseñando una linea de ropa intima para mujeres, hago ejercicio minimo 5 días a la semana, cuido mi alimentación y me siento la mujer mas plena y feliz en este mommento. </p>
                    <p class="post-meta">
                    Si tienes un sueño lucha y trabaja por el y nunca permitas que absolutamente nadie te diga que no puedes hacer las cosas. 
                    </p>
                </div>
            </div>
            <!-- Divider-->
            <hr class="my-4" />
        </div>
  
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Arletina 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>