my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("history/", include("history.urls")),
    path("hobbie/", include("hobbie.urls")),
    path("shop/", include("shop.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"
urlpatterns = [
    path("shops", views.ShopListView.as_view(), name="shop-list"),
    path("shop/add/", views.ShopCreateView.as_view(), name="shop-add"),
    path("shop/<int:pk>/detail/", views.ShopDetailView.as_view(), name="shop-detail"),
    path("shop/<int:pk>/update/", views.ShopUpdateView.as_view(), name="shop-update"),
    path("shop/<int:pk>/delete/", views.ShopDeleteView.as_view(), name="shop-delete"),
]

my_blog/shop/models.py
from django.db import models


class Shop(models.Model):
    name = models.CharField(max_length=40)
    modelo = models.CharField(max_length=40)
    email = models.EmailField()
    collection = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.name} {self.modelo}"

my_blog/shop/forms.py
from django import forms

from shop.models import Shop

class ShopForm(forms.ModelForm):
    name = forms.CharField(
        label="Nombre del producto",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "producto-name",
                "placeholder": "Nombre del producto",
                "required": "True",
            }
        ),
    )
    modelo = forms.CharField(
        label="Modelo",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "shop-modelo",
                "placeholder": "Modelo",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "shop-email",
                "placeholder": "Correo de contacto",
                "required": "True",
            }
        ),
    )
    collection = forms.CharField(
        label="Colección:",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "shop-collection",
                "placeholder": "Colección",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Shop
        fields = ["name", "modelo", "email", "collection"]

my_blog/shop/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from shop.models import Shop
from shop.forms import ShopForm


class ShopListView(ListView):
    model = Shop
    paginate_by = 5


class ShopDetailView(DetailView):
    model = Shop
    fields = ["name", "modelo", "email", "collection"]


class ShopCreateView(LoginRequiredMixin, CreateView):
    model = Shop
    success_url = reverse_lazy("shop:shop-list")

    form_class = ShopForm

    def form_valid(self, form):
        """Filter to avoid duplicate shops"""
        data = form.cleaned_data
        actual_objects = Shop.objects.filter(
            name=data["name"],
            modelo=data["modelo"],
            email=data["email"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El Producto {data['name']} - {data['modelo']} ya está creado",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Producto: {data['name']} Creado exitosamente!",
            )
            return super().form_valid(form)


class ShopUpdateView(LoginRequiredMixin, UpdateView):
    model = Shop
    fields = ["name", "modelo", "email", "collection"]

    def get_success_url(self):
        shop_id = self.kwargs["pk"]
        return reverse_lazy("shop:shop-detail", kwargs={"pk": shop_id})


class ShopDeleteView(LoginRequiredMixin, DeleteView):
    model = Shop
    success_url = reverse_lazy("shop:shop-list")

my_blog/shop/templates/shop/shop_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Eliminar Producto
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ shop.name }}</h1>
                    <p class="col-lg-10 fs-4 subheading">Eliminar Producto</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h3 class="col-lg-10 fs-4 subheading">Estás seguro de eliminar el producto: {{ shop.name }}?</h3>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger text-uppercase" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/shop/templates/shop/shop_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Productos Detalle
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ shop.name }} {{ shop.modelo }} </h1>
                    <p class="col-lg-10 fs-4 subheading">Linea Arletina Intima</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-add' %}">Crear nuevo producto</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Tipo: {{ shop.name }}</h3>
    <p class="col-lg-10 fs-5 subheading post-meta">Colección: {{ shop.collection }}</p>
    <div class="mx-auto">
        <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-update' shop.id %}"><i class="fa fa-pencil"></i> Editar</a>
        <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-delete' shop.id %}"><i class="fa fa-trash"></i> Eliminar</a>
    </div>
</div>
{% endblock %}

my_blog/shop/templates/shop/shop_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Productos Crear - Editar
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Edita el producto</h1>
                    <p class="col-lg-10 fs-4 subheading">Linea Arletina Intima</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary text-uppercase" value="Guardar producto" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/shop/templates/shop/shop_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Productos
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Conoce mi linea de productos</h1>
                    <p class="col-lg-10 fs-4 subheading">Linea Arletina Intima ¡Te fascinara!</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-add' %}">Crear nuevo producto</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <h3 class="col-lg-10 fs-4 subheading text-center">Linea Arletina Intima</h3>
    <hr class="my-4" />
    {% for shop in shop_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'shop:shop-detail' shop.id %}">
                <h3 class="col-lg-10 fs-4 subheading">Producto: {{ shop.name }}</h3>
            </a>
                <p class="col-lg-10 fs-5 subheading post-meta">Tipo: {{ shop.modelo }}</p>
                <p class="post-meta">Colección: {{ shop.collection }}</p>
            <div class="mx-auto">
                <a class="btn btn-primary text-uppercase" href="{% url 'shop:shop-detail' shop.id %}">Ver producto →</a>
            </div>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}