my_blog/hobbie/urls.py
from django.urls import path

from hobbie import views

app_name = "hobbie"
urlpatterns = [
    path("hobbies", views.HobbieListView.as_view(), name="hobbie-list"),
    path("hobbie/add/", views.HobbieCreateView.as_view(), name="hobbie-add"),
    path("hobbie/<int:pk>/detail/", views.HobbieDetailView.as_view(), name="hobbie-detail"),
    path("hobbie/<int:pk>/update/", views.HobbieUpdateView.as_view(), name="hobbie-update"),
    path("hobbie/<int:pk>/delete/", views.HobbieDeleteView.as_view(), name="hobbie-delete"),
]

my_blog/home/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path('avatar/load', views.avatar_load, name='avatar-load'),
    path("register/", views.register, name="user-register"),
    path('register/update/', views.user_update, name='user-update'),
    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/change-password.html',
            success_url=reverse_lazy("home:password-change-done")
        ),
        name="password-change"
    ),
    path(
        'password_change/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='registration/change-password-done.html'
        ),
        name="password-change-done"
    ),
]

my_blog/my_blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("history/", include("history.urls")),
    path("hobbie/", include("hobbie.urls")),
    path("shop/", include("shop.urls")),
]

if settings.DEBUG:
     from django.conf.urls.static import static
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/hobbie/models.py
from django.db import models

class Hobbie(models.Model):
    name = models.CharField(max_length=40)
    description = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return f"{self.name} | email: {self.email}"

my_blog/hobbie/forms.py
from django import forms

from hobbie.models import Hobbie

class HobbieForm(forms.ModelForm):
    name = forms.CharField(
        label="Pasatiempo",
        max_length=40,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "hobbie-name",
                "placeholder": "Pasatiempo",
                "required": "True",
            }
        ),
    )
    description = forms.CharField(
        label="Descripción",
        max_length=100,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "hobbie-description",
                "placeholder": "Descripción",
                "required": "True",
            }
        ),
    )
    email = forms.EmailField(
        label="Email:",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "hobbie-email",
                "placeholder": "email",
                "required": "True",
            }
        ),
    )

    class Meta:
        model = Hobbie
        fields = ["name", "description", "email"]

my_blog/hobbie/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from hobbie.models import Hobbie
from hobbie.forms import HobbieForm


class HobbieListView(ListView):
    model = Hobbie
    paginate_by = 5


class HobbieDetailView(DetailView):
    model = Hobbie
    fields = ["name", "description", "email"]


class HobbieCreateView(LoginRequiredMixin, CreateView):
    model = Hobbie
    success_url = reverse_lazy("hobbie:hobbie-list")

    form_class = HobbieForm

    def form_valid(self, form):
        """Filter to avoid duplicate hobbies"""
        data = form.cleaned_data
        actual_objects = Hobbie.objects.filter(
            name=data["name"],
            description=data["description"],
            email=data["email"],
        ).count()
        if actual_objects:
            messages.error(
                self.request,
                f"El Pasatiempo {data['name']} ya existe",
            )
            form.add_error("name", ValidationError("Acción no válida"))
            return super().form_invalid(form)
        else:
            messages.success(
                self.request,
                f"Pasatiempo: {data['name']} Creado exitosamente!",
            )
            return super().form_valid(form)


class HobbieUpdateView(LoginRequiredMixin, UpdateView):
    model = Hobbie
    fields = ["name", "description", "email"]

    def get_success_url(self):
        hobbie_id = self.kwargs["pk"]
        return reverse_lazy("hobbie:hobbie-detail", kwargs={"pk": hobbie_id})


class HobbieDeleteView(LoginRequiredMixin, DeleteView):
    model = Hobbie
    success_url = reverse_lazy("hobbie:hobbie-list")

my_blog/hobbie/templates/hobbie/hobbie_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Eliminar pasatiempo
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ hobbie.name }}</h1>
                    <p class="col-lg-10 fs-4 subheading">Eliminar Pasatiempo</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h3 class="col-lg-10 fs-4 subheading">Estás seguro de eliminar el Pasatiempo: {{ hobbie.name }}?</h3>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger text-uppercase" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-list' %}" >Cancelar</a>
</form>

{% endblock %}

my_blog/hobbie/templates/hobbie/hobbie_detail.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Detalle Pasatiempo
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">{{ hobbie.name }} </h1>
                    <p class="col-lg-10 fs-4 subheading">Detalles de tu pasatiempo</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-add' %}">Platicame tu pasatiempo</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Pasatiempo: {{ hobbie.name }}</h3>
    <p class="col-lg-10 fs-5 subheading post-meta">{{ hobbie.description}}</p>
    <div class="mx-auto">
        <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-update' hobbie.id %}"><i class="fa fa-pencil"></i> Editar</a>
        <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-delete' hobbie.id %}"><i class="fa fa-trash"></i> Eliminar</a>
    </div>
</div>
{% endblock %}

my_blog/hobbie/templates/hobbie/hobbie_form.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Edita tu pasatiempo
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Edita tu pasatiempo</h1>
                    <p class="col-lg-10 fs-4 subheading">El diario de Arletina</p>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary text-uppercase" value="Guardar pasatiempo" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

my_blog/hobbie/templates/hobbie/hobbie_list.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Pasatiempos
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/header-arletina.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row align-items-center gx-4 gx-lg-5">
            <div class="col-md-10 col-lg-8 col-xl-7 text-center text-lg-start">
                <div class="text-center text-lg-start site-heading">
                    <h1 class="display-4 fw-bold lh-1 mb-3">Pasatiempos</h1>
                    <p class="col-lg-10 fs-4 subheading">El diario de Arletina</p>
                    <div class="mx-auto">
                        <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-add' %}">Platicame tu pasatiempo</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <h3 class="col-lg-10 fs-4 subheading text-center">Nuestros pasatiempos</h3>
    <hr class="my-4" />
    {% for hobbie in hobbie_list %}
    
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'hobbie:hobbie-detail' hobbie.id %}">
                <h3 class="col-lg-10 fs-4 subheading">Pasatiempo: {{ hobbie.name }} </h3>
            </a>
                <p class="col-lg-10 fs-5 subheading post-meta">{{ hobbie.description}}</p>
                <p class="post-meta">{{ hobbie.email }}</p>
            <div class="mx-auto">
                <a class="btn btn-primary text-uppercase" href="{% url 'hobbie:hobbie-detail' hobbie.id %}">Leer mas →</a>
            </div>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}